name: weeklyplannerr
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  percent_indicator: ^2.1.5
  path_provider: ^1.6.11
  sqflite: ^1.3.0
  date_time_format: ^1.0.0+4
  flutter_spinkit: ^4.1.2
  cupertino_icons: ^0.1.3
  url_launcher: ^5.4.11
  provider: ^4.1.3
  frino_icons: ^1.0.1+4

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: BalsamiqSans
      fonts:
        - asset: fonts/BalsamiqSans-Regular.ttf

    - family: Merienda
      fonts:
        - asset: fonts/Merienda-Regular.ttf
